apps/recipes/urls.py
from django.urls import path

from apps.recipes import views


app_name = 'recipes'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/', views.RecipeCreateView.as_view(), name='new'),
    path('favorites/', views.FavoriteView.as_view(), name='favorites'),
    path('purchases/', views.PurchaseView.as_view(), name='purchases'),
    path(
        'purchases/download/',
        views.DownloadPurchasesListView.as_view(),
        name='purchases_download',
    ),
    path('follow/', views.FollowView.as_view(), name='follow'),
    path('<str:username>/', views.ProfileView.as_view(), name='profile'),
    path(
        '<str:username>/<int:pk>/',
        views.RecipeView.as_view(),
        name='recipe',
    ),
    path(
        '<str:username>/<int:pk>/edit/',
        views.RecipeUpdateView.as_view(),
        name='recipe_edit',
    ),
    path(
        '<str:username>/<int:pk>/delete/',
        views.RecipeDeleteView.as_view(),
        name='recipe_delete',
    ),
]

server/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import include, path


handler404 = 'apps.core.errors.page_not_found'  # noqa: WPS440, F811
handler500 = 'apps.core.errors.server_error'  # noqa: WPS440, F811

urlpatterns = [
    path('auth/', include('apps.users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('apps.api.urls')),
    path('about/', include('apps.about.urls', namespace='about')),
    path('', include('apps.recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    from django.conf.urls.static import static  # noqa: WPS433

    urlpatterns += static(  # type: ignore
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

apps/recipes/models/favorites.py
from django.contrib.auth import get_user_model
from django.db import models

from apps.recipes.models.recipes import Recipe


User = get_user_model()


class Favorite(models.Model):
    """Model definition for Favorite."""

    user = models.ForeignKey(
        to=User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE,
        related_name='favorites',
    )
    recipe = models.ForeignKey(
        to=Recipe,
        verbose_name='Рецепт',
        on_delete=models.CASCADE,
        related_name='favorites',
    )

    class Meta:  # noqa: WPS306
        """Meta definition for Favorite."""

        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранные'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'recipe'],
                name='unique_favorite_user_recipe',
            ),
        ]

    def __str__(self):
        """Unicode representation of Favorite."""
        return '{0} -> {1}'.format(self.user.username, self.recipe.name)

apps/recipes/models/follow.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:  # noqa: WPS306
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_user_author',
            ),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='user_not_author',
            ),
        ]

apps/recipes/models/ingredients.py
from django.db import models


_TITLE_MAX_LENGTH = 100
_DIMENSION_MAX_LENGTH = 20


class Ingredient(models.Model):
    name = models.CharField(
        max_length=_TITLE_MAX_LENGTH,
        verbose_name='Наименование',
    )
    dimension = models.CharField(
        max_length=_DIMENSION_MAX_LENGTH,
        verbose_name='Единицы измерения',
    )

    class Meta:  # noqa: WPS306
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'

    def __str__(self):
        return '{0}, {1}'.format(self.name, self.dimension)

apps/recipes/models/purchases.py
from django.contrib.auth import get_user_model
from django.db import models

from apps.recipes.models.recipes import Recipe


User = get_user_model()


class Purchase(models.Model):
    """Model definition for Purchase."""

    user = models.ForeignKey(
        to=User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE,
        related_name='purchases',
    )
    recipe = models.ForeignKey(
        to=Recipe,
        verbose_name='Рецепт',
        on_delete=models.CASCADE,
        related_name='purchases',
    )

    class Meta:  # noqa: WPS306
        """Meta definition for Purchase."""

        verbose_name = 'Покупка'
        verbose_name_plural = 'Покупки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'recipe'],
                name='unique_purchase_user_recipe',
            ),
        ]

    def __str__(self):
        """Unicode representation of Purchase."""
        return '{0} -> {1}'.format(self.user.username, self.recipe.name)

apps/recipes/models/recipes.py
from django.contrib.auth import get_user_model
from django.db import models

from apps.recipes.models.ingredients import Ingredient
from apps.recipes.models.tags import Tag


_NAME_MAX_LENGTH = 100
User = get_user_model()


class Recipe(models.Model):
    name = models.CharField(
        max_length=_NAME_MAX_LENGTH,
        verbose_name='Название',
    )
    image = models.ImageField(
        upload_to='recipes/',
        verbose_name='Картинка',
    )
    text = models.TextField(verbose_name='Описание')
    cooking_time = models.PositiveIntegerField(
        verbose_name='Время приготовления в минутах',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата публикации рецепта',
    )

    author = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор рецепта',
    )
    tags = models.ManyToManyField(to=Tag, verbose_name='Теги')
    ingredients = models.ManyToManyField(
        to=Ingredient,
        through='RecipeIngredient',
        verbose_name='Ингредиенты',
    )

    class Meta:  # noqa: WPS306
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ('-created_at', )

    def __str__(self):
        return self.name


class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey(to=Ingredient, on_delete=models.CASCADE)
    recipe = models.ForeignKey(to=Recipe, on_delete=models.CASCADE)
    amount = models.IntegerField(verbose_name='Количество')

    class Meta:  # noqa: WPS306
        verbose_name = 'Ингридиент рецепта'
        verbose_name_plural = 'Ингридиенты рецепта'

    def __str__(self):
        return self.ingredient.name

apps/recipes/models/tags.py
from django.db import models


_TAG_MAX_LENGTH = 10
_COLOR_MAX_LENGTH = 6


class TagChoices(models.TextChoices):
    BREAKFAST = 'breakfast', 'Завтрак'  # noqa: WPS115
    LUNCH = 'lunch', 'Обед'  # noqa: WPS115
    DINNER = 'dinner', 'Ужин'  # noqa: WPS115


class ColorChoices(models.TextChoices):
    GREEN = 'green', 'Зеленый'  # noqa: WPS115
    ORANGE = 'orange', 'Оранжевый'  # noqa: WPS115
    PURPLE = 'purple', 'Фиолетовый'  # noqa: WPS115


class Tag(models.Model):
    name = models.CharField(
        max_length=_TAG_MAX_LENGTH,
        choices=TagChoices.choices,
        default=TagChoices.LUNCH,
        unique=True,
        verbose_name='Название',
    )
    color = models.CharField(
        max_length=_COLOR_MAX_LENGTH,
        choices=ColorChoices.choices,
        default=ColorChoices.GREEN,
        unique=True,
        verbose_name='Цвет',
    )

    class Meta:  # noqa: WPS306
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name

apps/recipes/forms.py
from django import forms

from apps.recipes.models import Recipe, Tag
from apps.recipes.services import add_ingredients_to_recipe


class RecipeForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        label='Теги',
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    ingredients = forms.CharField(
        required=False,
        label='Ингредиенты',
        widget=forms.TextInput(attrs={'id': 'nameIngredient'}),
    )

    class Meta:  # noqa: WPS306
        model = Recipe
        fields = (
            'name',
            'tags',
            'ingredients',
            'cooking_time',
            'text',
            'image',
        )
        labels = {
            'name': 'Название рецепта',
            'cooking_time': 'Время приготовления',
            'image': 'Загрузить фото',
        }
        widgets = {
            'cooking_time': forms.TextInput(),
        }

    def clean_ingredients(self):
        ingredients = list(
            zip(
                self.data.getlist('nameIngredient'),  # type: ignore
                self.data.getlist('valueIngredient'),  # type: ignore
            ),
        )
        if not ingredients:
            raise forms.ValidationError('Отсутствуют ингредиенты')

        ingredients_clean = []
        for name, amount in ingredients:
            if int(amount) < 1:
                raise forms.ValidationError(
                    'Исправьте количество ингредиента "{0}"'.format(name),
                )
            else:
                ingredients_clean.append({
                    'name': name,
                    'amount': amount,
                })

        return ingredients_clean

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.save()
        ingredients = self.cleaned_data['ingredients']
        self.cleaned_data['ingredients'] = []
        self.save_m2m()
        add_ingredients_to_recipe(self.instance, ingredients)

        return instance

apps/recipes/views/favorites.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django_filters.views import BaseFilterView

from apps.recipes.filters import TagFilterSet
from apps.recipes.models import Recipe
from apps.recipes.views.mixins import TagContextMixin


class FavoriteView(
    LoginRequiredMixin,
    TagContextMixin,
    BaseFilterView,
    ListView,
):
    model = Recipe
    template_name = 'recipes/favorites.html'
    paginate_by = 6
    filterset_class = TagFilterSet

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(favorites__user=self.request.user)

apps/recipes/views/index.py
from django.db.models import Exists, OuterRef
from django.views.generic import ListView
from django_filters.views import BaseFilterView

from apps.recipes.filters import TagFilterSet
from apps.recipes.models import Favorite, Purchase, Recipe
from apps.recipes.views.mixins import TagContextMixin


class IndexView(TagContextMixin, BaseFilterView, ListView):
    model = Recipe
    template_name = 'recipes/index.html'
    paginate_by = 6
    filterset_class = TagFilterSet

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.request.user.is_authenticated:
            queryset = queryset.annotate(
                is_favorite=Exists(
                    Favorite.objects.filter(
                        user=self.request.user,
                        recipe=OuterRef('pk'),
                    ),
                ),
            ).annotate(
                is_purchase=Exists(
                    Purchase.objects.filter(
                        user=self.request.user,
                        recipe=OuterRef('pk'),
                    ),
                ),
            )
        return queryset

apps/recipes/views/mixins.py
from apps.recipes.models import Tag


class TagContextMixin:  # noqa: WPS306
    @property
    def extra_context(self):
        return {
            'active_tags': self.request.GET.getlist('tags'),
            'tags': Tag.objects.all(),
        }

apps/recipes/views/permissions.py
from django.shortcuts import redirect


class PermissionCheck:  # noqa: WPS306
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_superuser:
            if self.request.user.username != self.kwargs['username']:
                return redirect(
                    'recipes:recipe',
                    username=self.kwargs['username'],
                    pk=self.kwargs['pk'],
                )
        return super().dispatch(request, *args, **kwargs)

apps/recipes/views/profile.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from django_filters.views import BaseFilterView

from apps.recipes.filters import TagFilterSet
from apps.recipes.models import Recipe
from apps.recipes.views.mixins import TagContextMixin


User = get_user_model()


class ProfileView(TagContextMixin, BaseFilterView, ListView):
    model = Recipe
    template_name = 'recipes/profile.html'
    paginate_by = 6
    filterset_class = TagFilterSet

    def get_queryset(self):
        queryset = super().get_queryset()
        author = get_object_or_404(User, username=self.kwargs['username'])

        return queryset.filter(author=author)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = get_object_or_404(User, username=self.kwargs['username'])
        is_follower = False
        if self.request.user.is_authenticated:
            if self.request.user.follower.filter(author=author).exists():
                is_follower = True
        context['user_is_follower'] = is_follower
        context['author'] = author

        return context

apps/recipes/views/purchases.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse
from django.views import View
from django.views.generic import ListView

from apps.recipes.models import Recipe
from apps.recipes.services import generate_pdf


class PurchaseView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/purchases.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(purchases__user=self.request.user)


class DownloadPurchasesListView(View):
    def get(self, request, *args, **kwargs):
        pdf = generate_pdf(request.user)

        return FileResponse(
            pdf,
            as_attachment=True,
            filename='purchases.pdf',
        )

apps/recipes/views/recipes.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView

from apps.recipes.forms import RecipeForm
from apps.recipes.models import Recipe
from apps.recipes.views.permissions import PermissionCheck


class RecipeView(DetailView):
    model = Recipe
    template_name = 'recipes/recipe.html'


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = 'recipes/add_recipe.html'
    form_class = RecipeForm
    success_url = reverse_lazy('recipes:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, PermissionCheck, UpdateView):
    model = Recipe
    template_name = 'recipes/add_recipe.html'
    form_class = RecipeForm
    success_url = reverse_lazy('recipes:index')


class RecipeDeleteView(LoginRequiredMixin, PermissionCheck, DeleteView):
    model = Recipe
    success_url = reverse_lazy('recipes:index')

apps/recipes/views/subscribers.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView


class FollowView(LoginRequiredMixin, ListView):
    model = get_user_model()
    template_name = 'recipes/follow.html'
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(  # yapf: disable
            following__user=self.request.user,
        ).order_by('-id')

templates/recipes/includes/author_card.html
<div class="card-user" data-author="{{ author.pk }}">
    <div class="card-user__header">
        <h2 class="card-user__title">{{ author.get_full_name|default:author.username }} </h2>
    </div>
    <div class="card-user__body">
        <ul class="card-user__items">
            {% for recipe in author.recipes.all|slice:":3" %}
                <li class="card-user__item">
                    {% include 'recipes/includes/recipe_preview.html' with recipe=recipe %}
                </li>
            {% endfor %}

            {% if author.recipes.count > 3 %}
                <li class="card-user__item">
                    <a href="{% url 'recipes:profile' username=author.username %}" class="card-user__link link">Еще {{ author.recipes.count|add:"-3" }} рецептов...</a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="card-user__footer">
        <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
    </div>
</div>

templates/recipes/includes/button_favorite.html
{% url 'recipes:favorites' as favorites %}
{% if recipe.is_favorite or request.path == favorites %}
    <button class="button button_style_none" name="favorites">
        <span class="icon-favorite icon-favorite_active"></span>
    </button>
{% else %}
    <button class="button button_style_none" name="favorites" data-out>
        <span class="icon-favorite"></span>
    </button>
{% endif %}

templates/recipes/includes/button_favorite_recipe.html
{% load user_filters %}
{% if user.is_authenticated %}
    {% is_favorite as is_favorite_flag %}
    {% if is_favorite_flag %}
        <div class="single-card__favorite">
            <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_big icon-favorite_active"></span></button>
        </div>
    {% else %}
        <div class="single-card__favorite">
            <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite icon-favorite_big"></span></button>
        </div>
    {% endif %}
{% endif %}

templates/recipes/includes/button_purchase.html
{% if flag %}
    <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Рецепт добавлен</button>
{% else %}
    <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
{% endif %}

templates/recipes/includes/button_subscribe.html
{% url 'recipes:profile' username=author.username as url_profile %}
{% if user.is_authenticated and user != author %}
    {% if request.path == url_profile %}
        <div class="author-subscribe" data-author="{{ author.pk }}">
            <p style="padding: 0 0 2em 0;">
                {% if user_is_follower %}
                    <button class="button button_style_light-blue button_size_subscribe" name="subscribe">Отписаться от автора</button>
                {% else %}
                    <button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button>
                {% endif %}
                </p>
            </div>
    {% else %}
        {% comment %} Страница рецепта {% endcomment %}
        {% load user_filters %}
        {% is_follower as is_follower_flag %}
        <li class="single-card__item">
            {% if is_follower_flag %}
                <button class="button button_style_light-blue button_size_subscribe" name="subscribe">Отписаться от автора</button>
            {% else %}
                <button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button>
            {% endif %}
        </li>
    {% endif %}
{% endif %}

templates/recipes/includes/paginator.html
{% load user_filters %}
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if items.has_previous %}
            <li class="pagination__item">
                <a class="pagination__link link" href="?{% param_replace page=items.previous_page_number %}">
                    <span class="icon-left"></span>
                </a>
            </li>
        {% endif %}

        {% for page_number in paginator.page_range %}
            <li class="pagination__item {% if items.number == page_number %}pagination__item_active{% endif %}">
                <a class="pagination__link link" href="?{% param_replace page=page_number %}">{{ page_number }}</a>
            </li>
        {% endfor %}


        {% if items.has_next %}
            <li class="pagination__item">
                <a class="pagination__link link" href="?{% param_replace page=items.next_page_number %}">
                    <span class="icon-right"></span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/recipes/includes/recipe_card.html
<div class="card" data-id="{{ recipe.pk }}">
    <a href="{% url 'recipes:recipe' username=recipe.author.username pk=recipe.id %}" class="link" target="_blank">

        {% load thumbnail %}
        {% thumbnail recipe.image "364x240" crop="center" upscale=True as im %}
            <img src="{{ im.url }}" alt="{{ recipe.name }}" class="card__image">
        {% endthumbnail %}
    </a>

    <div class="card__body">
        <a class="card__title link" href="{% url 'recipes:recipe' username=recipe.author.username pk=recipe.id %}" target="_blank">{{ recipe.name }}</a>
        <ul class="card__items">
            {% for tag in recipe.tags.all %}
                <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.get_name_display }}</span></li>
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
            <p class="card__text"><span class="icon-user"></span> <a href="{% url 'recipes:profile' username=recipe.author.username %}" style="color: black"> {{ recipe.author.get_full_name|default:recipe.author.username }}</a></p>
        </div>
    </div>

    {% if user.is_authenticated %}
        <div class="card__footer">
            {% include 'recipes/includes/button_purchase.html' with flag=recipe.is_purchase %}
            {% include 'recipes/includes/button_favorite.html' with recipe=recipe %}
        </div>
    {% endif %}

</div>

templates/recipes/includes/recipe_preview.html
<div class="recipe">
    {% load thumbnail %}
    {% thumbnail recipe.image "500x500" crop="center" upscale=False as im %}
        <img src="{{ im.url }}" alt="{{ recipe.name }}" class="recipe__image">
    {% endthumbnail %}
    <h3 class="recipe__title">{{ recipe.name }}</h3>
    <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
</div>

templates/recipes/includes/recipe_purchases_preview.html
<li class="shopping-list__item" data-id="{{ recipe.pk }}">
    <div class="recipe recipe_reverse">
        {% load thumbnail %}
        {% thumbnail recipe.image "500x500" crop="center" upscale=False as im %}
            <img src="{{ im.url }}" alt="{{ recipe.name }}" class="recipe__image recipe__image_big">
        {% endthumbnail %}
        <h3 class="recipe__title">{{ recipe.name }}</h3>
        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
    </div>
    <a href="#" class="shopping-list__button link">Удалить</a>
</li>

templates/recipes/includes/tags.html
{% load user_filters %}
<ul class="tags">
    {% for tag in tags %}
        <li class="tags__item">
            <a id="{{ tag.name }}"
                class="tags__checkbox tags__checkbox_style_{{ tag.color }} {% if tag.name in active_tags %} tags__checkbox_active {% endif %}"
                href="?{% manage_tags tag=tag.name %}">
            </a>
            <span class="tags__label">{{ tag.get_name_display }}</span>
        </li>
    {% endfor %}
</ul>