apps/about/urls.py
from django.urls import path

from apps.about import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

apps/recipes/urls.py
from django.urls import path

from apps.recipes import views


app_name = 'recipes'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/', views.RecipeCreateView.as_view(), name='new'),
    path('favorites/', views.FavoriteView.as_view(), name='favorites'),
    path('purchases/', views.PurchaseView.as_view(), name='purchases'),
    path(
        'purchases/download/',
        views.DownloadPurchasesListView.as_view(),
        name='purchases_download',
    ),
    path('follow/', views.FollowView.as_view(), name='follow'),
    path('<str:username>/', views.ProfileView.as_view(), name='profile'),
    path(
        '<str:username>/<int:pk>/',
        views.RecipeView.as_view(),
        name='recipe',
    ),
    path(
        '<str:username>/<int:pk>/edit/',
        views.RecipeUpdateView.as_view(),
        name='recipe_edit',
    ),
    path(
        '<str:username>/<int:pk>/delete/',
        views.RecipeDeleteView.as_view(),
        name='recipe_delete',
    ),
]

server/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import include, path


handler404 = 'apps.core.errors.page_not_found'  # noqa: WPS440, F811
handler500 = 'apps.core.errors.server_error'  # noqa: WPS440, F811

urlpatterns = [
    path('auth/', include('apps.users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('apps.api.urls')),
    path('about/', include('apps.about.urls', namespace='about')),
    path('', include('apps.recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    from django.conf.urls.static import static  # noqa: WPS433

    urlpatterns += static(  # type: ignore
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

templates/includes/footer.html
<div class="footer__container container">
    <a href="{% url 'recipes:index' %}" class="footer__brand link">Продуктовый помощник</a>
    <ul class="footer__items">
        <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
        <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
    </ul>
</div>

templates/includes/nav.html
<nav class="nav">
    <div class="nav__container container">
    {% with url_name=request.resolver_match.url_name %}
        <ul class="nav__items list">
            <li class="nav__item
                {% if url_name == 'index' or url_name == 'recipe' or url_name == 'profile' %}nav__item_active{% endif %}
                {% if url_name == 'login' or url_name == 'signup' or url_name == 'password_reset' %}nav__item_disabled{% endif %}
                "><a href="{% url 'recipes:index' %}" class="nav__link link">Рецепты</a></li>
            {% if user.is_authenticated %}
                <li class="nav__item {% if url_name == 'follow' %}nav__item_active{% endif %}"><a href="{% url 'recipes:follow' %}" class="nav__link link">Мои подписки</a></li>
                <li class="nav__item {% if url_name == 'new' %}nav__item_active{% endif %}"><a href="{% url 'recipes:new' %}" class="nav__link link">Создать рецепт</a></li>
                <li class="nav__item {% if url_name == 'favorites' %}nav__item_active{% endif %}"><a href="{% url 'recipes:favorites' %}" class="nav__link link">Избранное</a></li>
                {% load user_filters %}
                <li class="nav__item {% if url_name == 'purchases' %}nav__item_active{% endif %}"><a href="{% url 'recipes:purchases' %}" class="nav__link link">Список покупок</a>
                    <span class="badge badge_style_blue nav__badge" id="counter">{% get_purchases_count %}</span>
                </li>
            {% endif %}
        </ul>

        <ul class="nav__items list">
            {% if user.is_authenticated %}
                <li class="nav__item {% if url_name == 'password_change' %}nav__item_active{% endif %}"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
            {% else %}
                <li class="nav__item {% if url_name == 'login' %}nav__item_active{% endif %}"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
            {% endif %}
        </ul>
    {% endwith %}
    </div>
</nav>