apps/recipes/urls.py
from django.urls import path

from apps.recipes import views


app_name = 'recipes'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/', views.RecipeCreateView.as_view(), name='new'),
    path('favorites/', views.FavoriteView.as_view(), name='favorites'),
    path('purchases/', views.PurchaseView.as_view(), name='purchases'),
    path(
        'purchases/download/',
        views.DownloadPurchasesListView.as_view(),
        name='purchases_download',
    ),
    path('follow/', views.FollowView.as_view(), name='follow'),
    path('<str:username>/', views.ProfileView.as_view(), name='profile'),
    path(
        '<str:username>/<int:pk>/',
        views.RecipeView.as_view(),
        name='recipe',
    ),
    path(
        '<str:username>/<int:pk>/edit/',
        views.RecipeUpdateView.as_view(),
        name='recipe_edit',
    ),
    path(
        '<str:username>/<int:pk>/delete/',
        views.RecipeDeleteView.as_view(),
        name='recipe_delete',
    ),
]

server/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import include, path


handler404 = 'apps.core.errors.page_not_found'  # noqa: WPS440, F811
handler500 = 'apps.core.errors.server_error'  # noqa: WPS440, F811

urlpatterns = [
    path('auth/', include('apps.users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('apps.api.urls')),
    path('about/', include('apps.about.urls', namespace='about')),
    path('', include('apps.recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    from django.conf.urls.static import static  # noqa: WPS433

    urlpatterns += static(  # type: ignore
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

apps/recipes/models/favorites.py
from django.contrib.auth import get_user_model
from django.db import models

from apps.recipes.models.recipes import Recipe


User = get_user_model()


class Favorite(models.Model):
    """Model definition for Favorite."""

    user = models.ForeignKey(
        to=User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE,
        related_name='favorites',
    )
    recipe = models.ForeignKey(
        to=Recipe,
        verbose_name='Рецепт',
        on_delete=models.CASCADE,
        related_name='favorites',
    )

    class Meta:  # noqa: WPS306
        """Meta definition for Favorite."""

        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранные'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'recipe'],
                name='unique_favorite_user_recipe',
            ),
        ]

    def __str__(self):
        """Unicode representation of Favorite."""
        return '{0} -> {1}'.format(self.user.username, self.recipe.name)

apps/recipes/models/follow.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:  # noqa: WPS306
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_user_author',
            ),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='user_not_author',
            ),
        ]

apps/recipes/models/ingredients.py
from django.db import models


_TITLE_MAX_LENGTH = 100
_DIMENSION_MAX_LENGTH = 20


class Ingredient(models.Model):
    name = models.CharField(
        max_length=_TITLE_MAX_LENGTH,
        verbose_name='Наименование',
    )
    dimension = models.CharField(
        max_length=_DIMENSION_MAX_LENGTH,
        verbose_name='Единицы измерения',
    )

    class Meta:  # noqa: WPS306
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'

    def __str__(self):
        return '{0}, {1}'.format(self.name, self.dimension)

apps/recipes/models/purchases.py
from django.contrib.auth import get_user_model
from django.db import models

from apps.recipes.models.recipes import Recipe


User = get_user_model()


class Purchase(models.Model):
    """Model definition for Purchase."""

    user = models.ForeignKey(
        to=User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE,
        related_name='purchases',
    )
    recipe = models.ForeignKey(
        to=Recipe,
        verbose_name='Рецепт',
        on_delete=models.CASCADE,
        related_name='purchases',
    )

    class Meta:  # noqa: WPS306
        """Meta definition for Purchase."""

        verbose_name = 'Покупка'
        verbose_name_plural = 'Покупки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'recipe'],
                name='unique_purchase_user_recipe',
            ),
        ]

    def __str__(self):
        """Unicode representation of Purchase."""
        return '{0} -> {1}'.format(self.user.username, self.recipe.name)

apps/recipes/models/recipes.py
from django.contrib.auth import get_user_model
from django.db import models

from apps.recipes.models.ingredients import Ingredient
from apps.recipes.models.tags import Tag


_NAME_MAX_LENGTH = 100
User = get_user_model()


class Recipe(models.Model):
    name = models.CharField(
        max_length=_NAME_MAX_LENGTH,
        verbose_name='Название',
    )
    image = models.ImageField(
        upload_to='recipes/',
        verbose_name='Картинка',
    )
    text = models.TextField(verbose_name='Описание')
    cooking_time = models.PositiveIntegerField(
        verbose_name='Время приготовления в минутах',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата публикации рецепта',
    )

    author = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор рецепта',
    )
    tags = models.ManyToManyField(to=Tag, verbose_name='Теги')
    ingredients = models.ManyToManyField(
        to=Ingredient,
        through='RecipeIngredient',
        verbose_name='Ингредиенты',
    )

    class Meta:  # noqa: WPS306
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ('-created_at', )

    def __str__(self):
        return self.name


class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey(to=Ingredient, on_delete=models.CASCADE)
    recipe = models.ForeignKey(to=Recipe, on_delete=models.CASCADE)
    amount = models.IntegerField(verbose_name='Количество')

    class Meta:  # noqa: WPS306
        verbose_name = 'Ингридиент рецепта'
        verbose_name_plural = 'Ингридиенты рецепта'

    def __str__(self):
        return self.ingredient.name

apps/recipes/models/tags.py
from django.db import models


_TAG_MAX_LENGTH = 10
_COLOR_MAX_LENGTH = 6


class TagChoices(models.TextChoices):
    BREAKFAST = 'breakfast', 'Завтрак'  # noqa: WPS115
    LUNCH = 'lunch', 'Обед'  # noqa: WPS115
    DINNER = 'dinner', 'Ужин'  # noqa: WPS115


class ColorChoices(models.TextChoices):
    GREEN = 'green', 'Зеленый'  # noqa: WPS115
    ORANGE = 'orange', 'Оранжевый'  # noqa: WPS115
    PURPLE = 'purple', 'Фиолетовый'  # noqa: WPS115


class Tag(models.Model):
    name = models.CharField(
        max_length=_TAG_MAX_LENGTH,
        choices=TagChoices.choices,
        default=TagChoices.LUNCH,
        unique=True,
        verbose_name='Название',
    )
    color = models.CharField(
        max_length=_COLOR_MAX_LENGTH,
        choices=ColorChoices.choices,
        default=ColorChoices.GREEN,
        unique=True,
        verbose_name='Цвет',
    )

    class Meta:  # noqa: WPS306
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name

apps/recipes/forms.py
from django import forms

from apps.recipes.models import Recipe, Tag
from apps.recipes.services import add_ingredients_to_recipe


class RecipeForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        label='Теги',
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    ingredients = forms.CharField(
        required=False,
        label='Ингредиенты',
        widget=forms.TextInput(attrs={'id': 'nameIngredient'}),
    )

    class Meta:  # noqa: WPS306
        model = Recipe
        fields = (
            'name',
            'tags',
            'ingredients',
            'cooking_time',
            'text',
            'image',
        )
        labels = {
            'name': 'Название рецепта',
            'cooking_time': 'Время приготовления',
            'image': 'Загрузить фото',
        }
        widgets = {
            'cooking_time': forms.TextInput(),
        }

    def clean_ingredients(self):
        ingredients = list(
            zip(
                self.data.getlist('nameIngredient'),  # type: ignore
                self.data.getlist('valueIngredient'),  # type: ignore
            ),
        )
        if not ingredients:
            raise forms.ValidationError('Отсутствуют ингредиенты')

        ingredients_clean = []
        for name, amount in ingredients:
            if int(amount) < 1:
                raise forms.ValidationError(
                    'Исправьте количество ингредиента "{0}"'.format(name),
                )
            else:
                ingredients_clean.append({
                    'name': name,
                    'amount': amount,
                })

        return ingredients_clean

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.save()
        ingredients = self.cleaned_data['ingredients']
        self.cleaned_data['ingredients'] = []
        self.save_m2m()
        add_ingredients_to_recipe(self.instance, ingredients)

        return instance

apps/recipes/views/favorites.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django_filters.views import BaseFilterView

from apps.recipes.filters import TagFilterSet
from apps.recipes.models import Recipe
from apps.recipes.views.mixins import TagContextMixin


class FavoriteView(
    LoginRequiredMixin,
    TagContextMixin,
    BaseFilterView,
    ListView,
):
    model = Recipe
    template_name = 'recipes/favorites.html'
    paginate_by = 6
    filterset_class = TagFilterSet

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(favorites__user=self.request.user)

apps/recipes/views/index.py
from django.db.models import Exists, OuterRef
from django.views.generic import ListView
from django_filters.views import BaseFilterView

from apps.recipes.filters import TagFilterSet
from apps.recipes.models import Favorite, Purchase, Recipe
from apps.recipes.views.mixins import TagContextMixin


class IndexView(TagContextMixin, BaseFilterView, ListView):
    model = Recipe
    template_name = 'recipes/index.html'
    paginate_by = 6
    filterset_class = TagFilterSet

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.request.user.is_authenticated:
            queryset = queryset.annotate(
                is_favorite=Exists(
                    Favorite.objects.filter(
                        user=self.request.user,
                        recipe=OuterRef('pk'),
                    ),
                ),
            ).annotate(
                is_purchase=Exists(
                    Purchase.objects.filter(
                        user=self.request.user,
                        recipe=OuterRef('pk'),
                    ),
                ),
            )
        return queryset

apps/recipes/views/mixins.py
from apps.recipes.models import Tag


class TagContextMixin:  # noqa: WPS306
    @property
    def extra_context(self):
        return {
            'active_tags': self.request.GET.getlist('tags'),
            'tags': Tag.objects.all(),
        }

apps/recipes/views/permissions.py
from django.shortcuts import redirect


class PermissionCheck:  # noqa: WPS306
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_superuser:
            if self.request.user.username != self.kwargs['username']:
                return redirect(
                    'recipes:recipe',
                    username=self.kwargs['username'],
                    pk=self.kwargs['pk'],
                )
        return super().dispatch(request, *args, **kwargs)

apps/recipes/views/profile.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from django_filters.views import BaseFilterView

from apps.recipes.filters import TagFilterSet
from apps.recipes.models import Recipe
from apps.recipes.views.mixins import TagContextMixin


User = get_user_model()


class ProfileView(TagContextMixin, BaseFilterView, ListView):
    model = Recipe
    template_name = 'recipes/profile.html'
    paginate_by = 6
    filterset_class = TagFilterSet

    def get_queryset(self):
        queryset = super().get_queryset()
        author = get_object_or_404(User, username=self.kwargs['username'])

        return queryset.filter(author=author)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = get_object_or_404(User, username=self.kwargs['username'])
        is_follower = False
        if self.request.user.is_authenticated:
            if self.request.user.follower.filter(author=author).exists():
                is_follower = True
        context['user_is_follower'] = is_follower
        context['author'] = author

        return context

apps/recipes/views/purchases.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse
from django.views import View
from django.views.generic import ListView

from apps.recipes.models import Recipe
from apps.recipes.services import generate_pdf


class PurchaseView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/purchases.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(purchases__user=self.request.user)


class DownloadPurchasesListView(View):
    def get(self, request, *args, **kwargs):
        pdf = generate_pdf(request.user)

        return FileResponse(
            pdf,
            as_attachment=True,
            filename='purchases.pdf',
        )

apps/recipes/views/recipes.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView

from apps.recipes.forms import RecipeForm
from apps.recipes.models import Recipe
from apps.recipes.views.permissions import PermissionCheck


class RecipeView(DetailView):
    model = Recipe
    template_name = 'recipes/recipe.html'


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = 'recipes/add_recipe.html'
    form_class = RecipeForm
    success_url = reverse_lazy('recipes:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, PermissionCheck, UpdateView):
    model = Recipe
    template_name = 'recipes/add_recipe.html'
    form_class = RecipeForm
    success_url = reverse_lazy('recipes:index')


class RecipeDeleteView(LoginRequiredMixin, PermissionCheck, DeleteView):
    model = Recipe
    success_url = reverse_lazy('recipes:index')

apps/recipes/views/subscribers.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView


class FollowView(LoginRequiredMixin, ListView):
    model = get_user_model()
    template_name = 'recipes/follow.html'
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(  # yapf: disable
            following__user=self.request.user,
        ).order_by('-id')

templates/recipes/add_recipe.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% if recipe %}Редактирование рецепта{% else %}Создание рецепта{% endif %}{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'recipes/css/pages/form.css' %}">
{% endblock css %}

{% block header_title %}{% if recipe %}Редактирование рецепта{% else %}Создание рецепта{% endif %}{% endblock %}
{% block tags %}{% endblock tags %}
{% block content %}
{% load user_filters %}
<div class="form-container">
    <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form__group">
                <label for="{{ field.id_for_label }}" class="form__label">{{ field.label }}</label>
                <div class="form__field-group {% if field.name == 'cooking_time' %}form__field-group_time{% endif %}">
                    {% if field.name == 'tags' %}
                        <div class="tags">
                            {% for tag in form.fields.tags.choices.queryset %}
                                <div class="tags__item">
                                    <input  type="checkbox"
                                            name="tags"
                                            value="{{ tag.pk }}"
                                            id="id_tags_{{ forloop.counter }}"
                                            class="tags__checkbox tags__checkbox_style_{{ tag.color }}"
                                            {% if tag in recipe.tags.all %}checked=""{% endif %}>
                                    <label for="id_tags_{{ forloop.counter }}" class="tags__label">{{ tag.get_name_display }}</label>
                                </div>
                            {% endfor %}
                        </div>
                    {% elif field.name == 'ingredients' %}
                        <div class="form__field-group-ingredientes">
                            <div class="form__dropdown">
                                <input type="text" id="nameIngredient" class="form__input">
                                <div class="form__dropdown-items"></div>
                            </div>
                            <input type="number" id="cantidad" class="form__input" min="0">
                            <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                        </div>

                        <div class="form__field-group-ingredientes-container">
                            {% if recipe %}
                                {% for ingredient in recipe.recipeingredient_set.all %}
                                    <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
                                        <span> {{ ingredient.ingredient.name }} {{ ingredient.amount }} {{ ingredient.ingredient.dimension }}</span>
                                        <span class="form__field-item-delete"></span>
                                        <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient" type="hidden" value="{{ ingredient.ingredient.name }}">
                                        <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient" type="hidden" value="{{ ingredient.amount }}">
                                        <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient" type="hidden" value="{{ ingredient.ingredient.dimension }}">
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    {% elif field.name == 'text' %}
                        {{ field|addclass:"form__textarea" }}
                    {% elif field.name == 'cooking_time' %}
                        {{ field|addclass:"form__input" }}
                        <label for="id_time" class="form__label">минут</label>
                    {% elif field.name == 'image' %}
                        {{ field }}
                    {% else %}
                        {{ field|addclass:"form__input" }}
                    {% endif %}

                    {% if field.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <div class="form__footer">
            {% if recipe %}
                <button class="button button_style_blue">Сохранить</button>
                <a style="margin-left: 2.5em" href="{% url 'recipes:recipe_delete' username=recipe.author.username pk=recipe.pk %}" class="form__ingredient-link">Удалить</a>
            {% else %}
                <button class="button button_style_blue">Создать рецепт</button>
            {% endif %}
        </div>
    </form>
</div>
{% endblock content %}

{% block javascript %}
    <script src="{% static 'recipes/js/utils/debouncing.js' %}"></script>
    <script src="{% static 'recipes/js/formRecipe.js' %}"></script>
{% endblock javascript %}

templates/recipes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Title -->
    <title>{% block title %}Рецепты{% endblock %} | Foodgram</title>

    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'recipes/css/pages/index.css' %}">
</head>

<body class="body">
    <header class="header">
        {% include 'recipes/includes/nav.html' %}
    </header>

    <main class="main container">
        {% block content %}
        {% endblock content %}
    </main>

    <footer class="footer">
        {% include 'recipes/includes/footer.html' %}
    </footer>

    {% block javascript %}
    {% endblock javascript %}
</body>
</html>

templates/recipes/favorites.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Избранное{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'recipes/css/pages/index.css' %}">{% endblock css %}

{% block header_title %}Избранное{% endblock header_title %}
{% block content %}
    <div class="card-list">
        {% for recipe in page_obj %}
            {% include 'recipes/includes/recipe_card.html' with recipe=recipe %}
        {% endfor %}
    </div>

    {% if page_obj.has_other_pages %}
        {% include 'recipes/includes/paginator.html' with items=page_obj paginator=paginator %}
    {% endif %}
{% endblock content %}

{% block javascript %}
    <script src="{% static 'recipes/js/components/Favorites.js' %}"></script>
    <script src="{% static 'recipes/js/components/CardList.js' %}"></script>
    <script src="{% static 'recipes/js/favorite.js' %}"></script>
{% endblock javascript %}

templates/recipes/follow.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Мои подписки{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'recipes/css/pages/myFollow.css' %}">{% endblock css %}

{% block header_title %}Мои подписки{% endblock header_title %}
{% block tags %}{% endblock tags %}
{% block content %}
    <div class="card-list">
        {% for author in object_list %}
            {% include 'recipes/includes/author_card.html' with author=author %}
        {% endfor %}
    </div>

    {% if page_obj.has_other_pages %}
        {% include 'recipes/includes/paginator.html' with items=page_obj paginator=paginator %}
    {% endif %}
{% endblock content %}

{% block javascript %}
    <script src="{% static 'recipes/js/components/MyFollow.js' %}"></script>
    <script src="{% static 'recipes/js/components/Subscribe.js' %}"></script>
    <script src="{% static 'recipes/js/myFollow.js' %}"></script>
{% endblock javascript %}

templates/recipes/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="card-list">
{% for recipe in page_obj %}
    {% include 'recipes/includes/recipe_card.html' with recipe=recipe %}
{% endfor %}
</div>
{% if page_obj.has_other_pages %}
    {% include 'recipes/includes/paginator.html' with items=page_obj paginator=paginator %}
{% endif %}
{% endblock content %}

{% block javascript %}
    <script src="{% static 'recipes/js/components/CardList.js' %}"></script>
    {% if user.is_authenticated %}
        <script src="{% static 'recipes/js/components/Favorites.js' %}"></script>
        <script src="{% static 'recipes/js/indexAuth.js' %}"></script>
    {% else %}
        <script src="{% static 'recipes/js/indexNotAuth.js' %}"></script>
    {% endif %}
{% endblock javascript %}

templates/recipes/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Рецепты{% endblock %}

{% block header_title %}{{ author.get_full_name|default:author.username }}{% endblock header_title %}
{% block content %}
    {% include 'recipes/includes/button_subscribe.html' with author=author %}
    <div class="card-list">
        {% for recipe in page_obj %}
            {% include 'recipes/includes/recipe_card.html' with recipe=recipe %}
        {% endfor %}
    </div>

    {% if page_obj.has_other_pages %}
        {% include 'recipes/includes/paginator.html' with items=page_obj paginator=paginator %}
    {% endif %}
{% endblock content %}

{% block javascript %}
    <script src="{% static 'recipes/js/components/Favorites.js' %}"></script>
    <script src="{% static 'recipes/js/components/Subscribe.js' %}"></script>
    <script src="{% static 'recipes/js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'recipes/js/authorRecipe.js' %}"></script>
{% endblock javascript %}

templates/recipes/purchases.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Список покупок{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'recipes/css/pages/shopList.css' %}">{% endblock css %}

{% block header_title %}Список покупок{% endblock header_title %}
{% block tags %}{% endblock %}

{% block content %}
    <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for recipe in object_list %}
                {% include 'recipes/includes/recipe_purchases_preview.html' with recipe=recipe %}
            {% endfor %}
        </ul>

        {% if object_list.count %}
            <a href="{% url 'recipes:purchases_download' %}"><button class="button button_style_blue">Скачать список</button></a>
        {% endif %}
    </div>
{% endblock content %}

{% block javascript %}
    <script src="{% static 'recipes/js/components/ShopList.js' %}"></script>
    <script src="{% static 'recipes/js/shopList.js' %}"></script>
{% endblock javascript %}

templates/recipes/recipe.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'recipes/css/pages/single.css' %}">
{% endblock css %}

{% block header %}{% endblock %}
{% block content %}
<div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
    {% load thumbnail %}
    {% thumbnail recipe.image "500x500" crop="center" upscale=True as im %}
        <img src="{{ im.url }}" alt="{{ recipe.name }}" class="single-card__image">
    {% endthumbnail %}
    <div class="single-card__info">
        <div class="single-card__header-info">
            <h1 class="single-card__title">{{ recipe.name }}</h1>
            {% include 'recipes/includes/button_favorite_recipe.html' %}
        </div>
        <ul class="single-card__items">
            {% for tag in recipe.tags.all %}
                <li class="single-card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.get_name_display }}</span></li>
            {% endfor %}
        </ul>
        <div class="single-card__items single-card__items_column">
            <p class="single-card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
            {% if user.is_authenticated %}
                <ul class="single-card__items">
                    <li class="single-card__item"><p class="single-card__text"><span class="icon-user"></span> {{ recipe.author.get_full_name|default:recipe.author.username }}</p></li>
                    <li class="single-card__item"><a style="margin-left: 2.5em" href="{% url 'recipes:recipe_edit' username=recipe.author.username pk=recipe.pk %}" class="single-card__text">Редактировать рецепт</a></li>
                </ul>
            {% else %}
                <p class="single-card__text"><span class="icon-user"></span> {{ recipe.author.get_full_name|default:recipe.author.username }}</p>
            {% endif %}
        </div>

        {% if user.is_authenticated %}
            <ul class="single-card__items">
                {% load user_filters %}
                {% is_purchase as is_purchase_flag %}
                <li class="single-card__item">
                    {% include 'recipes/includes/button_purchase.html' with flag=is_purchase_flag %}
                </li>
                {% include 'recipes/includes/button_subscribe.html' with author=recipe.author %}
            </ul>
        {% endif %}

        <div class="single-card__section">
            <h3 class="single-card__section-title">Ингридиенты:</h3>
            <div class="single-card__items single-card__items_column">
                {% for ingr in recipe.recipeingredient_set.all %}
                    <p class=" single-card__section-item">{{ ingr.ingredient.name }} - {{ ingr.amount }} {{ ingr.ingredient.dimension }}</p>
                {% endfor %}
            </div>
        </div>
        <div class="single-card__section">
            <h3 class="single-card__section-title">Описание:</h3>
            <p class=" single-card__section-text">{{ recipe.text }}</p>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
    <script src="{% static 'recipes/js/components/SingleCard.js' %}"></script>
    <script src="{% static 'recipes/js/components/CardList.js' %}"></script>

    {% if user.is_authenticated %}
        <script src="{% static 'recipes/js/components/Favorites.js' %}"></script>
        <script src="{% static 'recipes/js/components/Subscribe.js' %}"></script>
        <script src="{% static 'recipes/js/singlePage.js' %}"></script>
    {% else %}
        <script src="{% static 'recipes/js/singlePageNotAuth.js' %}"></script>
    {% endif %}
{% endblock javascript %}